def execute_macro(client):
    client.ContextPath = "\System\Subsystem_1\ADMV8818 Board\ADMV8818"
    client.Run("@Wizards")

    
    client.WriteRegister("0", "60")
    client.WriteRegister("1", "0")
    client.WriteRegister("3", "1")
    client.WriteRegister("4", "24")
    client.WriteRegister("5", "136")
    client.WriteRegister("16", "0")
    client.WriteRegister("17", "4")
    client.WriteRegister("18", "0")
    client.WriteRegister("19", "0")
    client.WriteRegister("20", "0")
    client.WriteRegister("32", "0")
    client.WriteRegister("33", "15")
    client.WriteRegister("34", "201")
    client.WriteRegister("35", "15")
    client.WriteRegister("36", "18")
    client.WriteRegister("37", "15")
    client.WriteRegister("38", "27")
    client.WriteRegister("39", "15")
    client.WriteRegister("40", "36")
    client.WriteRegister("41", "15")
    client.WriteRegister("256", "200")
    client.WriteRegister("257", "0")
    client.WriteRegister("258", "200")
    client.WriteRegister("259", "48")
    client.WriteRegister("260", "200")
    client.WriteRegister("261", "112")
    client.WriteRegister("262", "200")
    client.WriteRegister("263", "176")
    client.WriteRegister("264", "200")
    client.WriteRegister("265", "240")
    client.Run("@ApplySettings")

    '''
    client.SetByteParameter("HPF_WR1", "0", "-1")
    client.SetIntParameter("virtual-parameter-displayed-rfin-switch-position", "3", "-1")
    client.SetByteParameter("virtual-parameter-displayed-hpf", "7", "-1")
    client.SetIntParameter("virtual-parameter-displayed-rfout-switch-position", "3", "-1")
    client.SetByteParameter("virtual-parameter-displayed-lpf", "7", "-1")
    print("done")
    '''